export const content = {
  nav: [
    { id: 'about', label: 'About' },
    { id: 'skills', label: 'My Skills' },
    { id: 'experience', label: 'Experience' },
    { id: 'contact', label: 'Contact' },
  ],
  hero: {
    intro: "I'M",
    name: 'NHAN HOANG',
    role: 'Front-end Developer',
    summary:
      'Front-end Developer.',
    cta: 'Download CV',
  },
  about:
    "With over 2 years of proven experience, I'm passionate about building robust and user-centric web applications. Currently focused on (specific area).",
  skills: [
    {
      key: 'react',
      level: 'Intermediate',
      title: 'ReactJS',
      note: '',
    },
    {
      key: 'htmlcss',
      level: 'Intermediate',
      title: 'HTML & CSS',
      note: '',
    },
    {
      key: 'javascript',
      level: 'Intermediate',
      title: 'JavaScript',
      note: '',
    },
    {
      key: 'typescript',
      level: 'Intermediate',
      title: 'TypeScript',
      note: '',
    },
    {
      key: 'redux',
      level: 'Intermediate',
      title: 'Redux',
      note: '',
    },
    {
      key: 'git',
      level: 'Intermediate',
      title: 'Git',
      note: '',
    },
    {
      key: 'mongodb',
      level: 'Intermediate',
      title: 'MongoDB',
      note: '',
    },
    {
      key: 'tailwindcss',
      level: 'Intermediate',
      title: 'Tailwind CSS',
      note: '',
    },
    {
      key: 'antdesign',
      level: 'Intermediate',
      title: 'Ant Design',
      note: '',
    },
    {
      key: 'mui',
      level: 'Intermediate',
      title: 'MUI',
      note: '',
    },
    {
      key: 'api',
      level: 'Advanced',
      title: 'RESTful API',
      note: '',
    },
    {
      key: 'responsive',
      level: 'Experienced',
      title: 'Responsive Design',
      note: '',
    },
  ],
  experience: [
    {
      range: '2025 - present',
      role: 'Freelancer Web developer',
      company: 'Freelance Projects',
      bullets: [
        'AISVISA.US: Design and deploy immigration support website using WordPress.',
        'THEGLAMPCO.COM: Design and implement a luxury camping introduction and booking website.',
        'Managed and developed over 10+ professional websites for clients in various industries, primarily focused on WordPress solutions.',
      ],
      keyProjects: [
        'AISVISA.US',
        'THEGLAMPCO.COM',
      ],
      tags: ['WordPress', 'Freelance', 'E-commerce', 'Education Sites'],
    },
    {
      range: '2022 - 2024',
      role: 'Software Implementation Consultant',
      company: 'VNPT Information Technology Center - Full time',
      bullets: [
        'Led software implementation and training after handover from Sales team.',
        'Managed customer expectations and ensured alignment with product scope.',
        'Delivered project updates and new feature information to clients.',
        'Acted as the customer voice, providing feature feedback to internal teams.',
        'Worked cross-functionally to achieve weekly/monthly KPIs.',
      ],
      keyProjects: [
        'VNPT iLIS – Land Information System (2024)',
        '1022 Information Portal – Information portal for receiving and answering information (2024)',
        'VNPT CCVC – Civil Servant Management System – Department of Home Affairs (2024)',
        'VNPT HRM, iOffice, iQMS, iStorage and Other ERP Solutions (2024)',
        'Social Security application – ASXH (2023-2024)',
        'Intelligent Operations Center (IOC) – Binh Chanh District (2022-2023)',
      ],
      tags: ['Software Implementation', 'Customer Success', 'ERP', 'VNPT'],
    },

  ],
  projects: [
    {
      title: 'BKaram',
      desc: 'A web application built with React, focusing on clean interface and interaction.',
      tags: ['React', 'JavaScript', 'CSS'],
      cta1: 'Live Demo',
      cta2: 'View on GitHub',
      repo: 'https://github.com/lenhanhoang98/bkaram',
      live: 'https://bkaram.vercel.app/',
    },
    {
      title: 'Anime Dictionary',
      desc: 'A React-based application for searching and exploring comprehensive anime information.',
      tags: ['React', 'JavaScript', 'CSS'],
      cta1: 'Live Demo',
      cta2: 'View on GitHub',
      repo: 'https://github.com/lenhanhoang98/anime-dictionary-app',
      live: 'https://anime-dictionary.netlify.app/',
    },
    {
      title: 'Crypto App',
      desc: 'Cryptocurrency market tracking application using React, Redux, and RapidAPI for real-time data.',
      tags: ['React', 'Redux', 'RapidAPI'],
      cta1: 'Live Demo',
      cta2: 'View on GitHub',
      repo: 'https://github.com/lenhanhoang98/crypto-app',
      live: 'https://crypto-self-project.netlify.app',
    },
    {
      title: 'AISVISA.US',
      desc: 'Custom WordPress development for Visa and Travel services.',
      tags: ['WordPress', 'Freelance'],
      cta1: 'Visit Site',
      live: 'https://aisvisa.us',
    },
    {
      title: 'The Glamp Co',
      desc: 'Luxury glamping and travel experience platform.',
      tags: ['WordPress', 'Freelance'],
      cta1: 'Visit Site',
      live: 'https://theglampco.com',
    },
  ],
  otherProjects: [
    { name: 'Neosho Beauty College', url: 'https://neoshobeautycollege.com', tags: ['WordPress', 'Elementor', 'Education'] },
    { name: 'Perimeter School', url: 'https://perimeter.school', tags: ['WordPress', 'School Management'] },
    { name: 'Aiken Beauty and Barber School', url: 'https://aikenbeautyandbarberschool.com', tags: ['WordPress', 'Education'] },
    { name: 'Atlanta Beauty Academy', url: 'https://atlantabeautyacademy.com', tags: ['WordPress', 'Education'] },
    { name: 'Dalton Institute', url: 'https://daltoninstitute.com', tags: ['WordPress', 'Education'] },
    { name: 'Hogan Ice', url: 'https://hoganice.edu', tags: ['WordPress', 'Education'] },
    { name: 'Beauty NWA', url: 'https://beautynwa.com', tags: ['WordPress', 'Education'] },
    { name: 'USA Beauty Academy', url: 'https://usa-beautyacademy.com', tags: ['WordPress', 'Education'] },
  ],
  contact: {
    form: {
      name: 'Name',
      email: 'Email',
      message: 'Message',
      send: 'Send',
    },
    info: {
      email: 'lenhanhoang98@gmail.com',
      phone: '(+84) 382960160',
      location: 'District 5, Ho Chi Minh City, Viet Nam',
      social: ['gh', 'in', 'mail'],
    },
    actions: {
      copy: 'Click-to-copy',
      link: 'Direct Link',
    },
  },
  footer: '© 2024 NHAN HOANG. Crafting experiences with code.',
}

